image: continuumio/miniconda3:4.7.12

stages: 
  - build
  - unit test
  - integration test 
 
before_script:
  - sudo apt-get install libevent-dev
  - conda env create ml -f environment.yml
  - conda activate ml

build:
  stage: build
  script:
    - echo "Build docker image"

unit_test:
  stage: unit test 
  script:
    - echo "Unit test"

integration_test:
  stage: integration test 
  script:
    - echo "integration test"
