stages: 
  - build image
  - unit test
  - integration test 

default:
  # image: continuumio/miniconda3:4.7.12
  image: docker:latest


Pre:
  stage: .pre 
  script:
    - echo "Pre stage:"
    - echo $CONDA_DEFAULT_ENV 

Build image:
  stage: build image
  script:
    - echo "Build docker image"
    - docker build . -f Dockerfile -t ml_dev 

Unit test:
  stage: unit test 
  script:
    - echo "Unit test"
    - echo $CONDA_DEFAULT_ENV

Integration test:
  stage: integration test 
  script:
    - echo "integration test"
    - echo $CONDA_DEFAULT_ENV

Post:
  stage: .post 
  script:
    - echo "post"