stages: 
  - build_image
  - unit_test
  - integration_test 

default:
  image: continuumio/miniconda3:4.7.12

  before_script:
    - sudo apt-get install libevent-dev
    - conda env create ml -f environment.yml
    - conda activate ml

Pre:
  stage: .pre 
  script:
    - echo "pre"

Build image:
  stage: build_image
  script:
    - echo "Build docker image"

Unit test:
  stage: unit_test 
  script:
    - echo "Unit test"

Integration test:
  stage: integration_test 
  script:
    - echo "integration test"

Post:
  stage: .post 
  script:
    - echo "post"

# production: