stages: 
  - build image
  - unit test
  - integration test 

default:
  image: docker:latest
  # image: alpine:3.11
  # image: continuumio/miniconda3:4.7.12
  services:
    - docker:dind

Pre:
  stage: .pre 
  script:
    - echo "Pre stage:"
    - echo $CONDA_DEFAULT_ENV 

Build image:
  stage: build image
  before_script:
    - docker info
    # - apt-get update
    # - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    # - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    # - apt-get install -y docker-ce docker-ce-cli containerd.io
  script:
    - echo "Build docker image"
    - docker build . -f Dockerfile -t ml_dev 

Unit test:
  stage: unit test 
  script:
    - echo "Unit test"
    - echo $CONDA_DEFAULT_ENV

Integration test:
  stage: integration test 
  script:
    - echo "integration test"
    - echo $CONDA_DEFAULT_ENV

Post:
  stage: .post 
  script:
    - echo "post"