name: ml
channels:
  - conda-forge
dependencies:
  - cached-property==1.5.1
  - matplotlib=3.0.1
  - numpy==1.15.4
  - pandas==0.24.2
  - pytest==5.2.1
  - python==3.7 
  - pyyaml==5.1.2
  - scipy==1.1.0
  - black==19.10b0
  - pyspark==2.4.4
  # - pathlib
  - scikit-learn
  - pip:
    - docker==3.7.1
    - joblib
    - featuretools